### ISSUE TITLE
Issue in material design version of the demo

### ISSUE THREAD

**Issue by joargp** [angular-data-grid/angular-data-grid.github.io#10]
The filtering does not seem to work
![image](https://cloud.githubusercontent.com/assets/1954952/14742173/0a0a61fe-089b-11e6-8bda-5149b7b8f60c.png)

**Comment by AlexanderZhukCoherent** [comment]
Issue fixed by https://github.com/angular-data-grid/angular-data-grid.github.io/commit/7d8ec4ae9c42d77f32154820a0b77dc1995d7e27, thanks
