### ISSUE TITLE
Text based filter does not filter out empty/null values

### ISSUE THREAD

**Issue by mir4ef** [angular-data-grid/angular-data-grid.github.io#11]
I am pulling data from a database and some of the fields have `null` values, which displays as empty cell in the grid (which it should). However, I have a text based filter (`filter-by="myfield"` `filter-type="text"`) on a column that has some empty values and these rows do not get filtered out (even if I type complete garbage). Here is a [codepen](http://codepen.io/mir4ef/pen/zqmqPX) to illustrate. The `order #` column has a `null` value and never gets filtered out of the results. If I missing something or I am not clear enough, please let me know :) thank you!

**Comment by korshuk** [comment]
Fixed. Fill free to use.

**Comment by mir4ef** [comment]
Great! Thank you!
