### ISSUE TITLE
modal popup

### ISSUE THREAD

**Issue by codeight** [angular-data-grid/angular-data-grid.github.io#12]
i'm added a action-colum with edit, delete icons. How can be handled a modal popup with given ID like
ng-click="open(c, 'lg');

**Comment by korshuk** [comment]
You can use this code: ng-click="open(item.id, 'lg')". Item - is data object for every row, and if it has id you'll get it. May be it is better to use  ng-click="open(item, 'lg')" to work with full object inside "open" function.
