### ISSUE TITLE
Custom filter doesn't work with checkboxes any more

### ISSUE THREAD

**Issue by mir4ef** [angular-data-grid/angular-data-grid.github.io#14]
Hi,

I have checkboxes (Angular Material's `<md-checkbox>`) that I use as custom filters to remove/add rows based on rules (e.i. exclude rows where the sale price is below $1, etc.). Everything used to work fine before one of the recent updates. Now, the `value` being passed to the filter is always `undefined`. However, the `ng-model` value is getting updated correctly. Here is a [codepen](http://codepen.io/mir4ef/pen/bZxZwp) to illustrate. As you can see in the example, when you check the checkbox, `ng-model` updates, but not the `customFilters`'s filter value. So I had to redeploy a version of `dataGrid(.min).js` I had from June 30th to get it working again. Here is a [codepen](http://codepen.io/mir4ef/pen/zBJzGp) with the older file that is working. As a side note, I am using Angular Material v1.0.9 on my dev and non dev environments, but the issue occurs even with plain checkboxes (as show in the codepens above). Also, as a test, I tried plain text `input`, but same result as `ng-model` is not being passed to the `customFilters`. Hope this helps! If I am missing something or I am not clear enough, please let me know :) Thank you!

**Comment by mir4ef** [comment]
Just found out that the last working version is before commit [38844a9](https://github.com/angular-data-grid/angular-data-grid.github.io/commit/38844a964285e2bd6beae5c1a78aeedf7ef78fc9), but hadn't had a chance to look at what changed for that commit. Hope this helps! Thank you!

**Comment by sskozzlovv** [comment]
Fixed in 2b80cb4
