### ISSUE TITLE
In case of bootstrap data grid drop down filter on column is not working

### ISSUE THREAD

**Issue by satishsomani** [angular-data-grid/angular-data-grid.github.io#16]
I am using same  code as per steps but when I work on drop down filter for status. Value is binding in that filter but based on selected value is not showing the data.

when I see your code in codepen(link provided by you) there also its not working, can any one help me how I fix it.
Codepen link http://codepen.io/AngularDataGrid/pen/xZddZm

**Comment by sskozzlovv** [comment]
@satishsomani This bug was fixed in 2b80cb4
