### ISSUE TITLE
How can I scroll through a list within the grid?

### ISSUE THREAD

**Issue by dhnheidmann** [angular-data-grid/angular-data-grid.github.io#17]
I set up my grid-options with an object that contains some attributes and one of these attributes is another list. I'm trying to go through this list and I'm not getting using ng-repeat.

`<div grid-data grid-options="TestGrid" grid-actions="gridActions">
    <table>
        <tr grid-item>
            <td ng-bind="item.Id"><td>
            <td>
                <ul>
                    <li ng-repeat="origem in item.Origem">
                        <a href="#">test</a>
                    </li>
                </ul>           
            </td>       
        </tr>       
    </table>
</div>`

Can you help me please?

**Comment by sskozzlovv** [comment]
grid-options object is used only for purposes listed in documentation(get data, sorting, filtering). If you need some list inside every item just add this list to every item in initial array.
$scope.gridOptions = {
  data: [
    {id: 1, name: 'test name', youtList: []},
    {id: 2, name: 'test name 2', youtList: []} 
  ]
};

**Comment by sskozzlovv** [comment]
Fixed in e60daba. (Fixed problem when grid-item contains directive with ng-transclude in template)
