### ISSUE TITLE
Filtering doesn't work in modal window

### ISSUE THREAD

**Issue by by12358** [angular-data-grid/angular-data-grid.github.io#18]
I'm using angular data grid in a modal window.  I've found that filtering doesn't seem to work in a modal window.  Stepping through the code, it seems that the issue lies with the registration of the filters at line 303:

angular.forEach(angular.element(document.querySelectorAll('[filter-by]')), function (filter) {

Document is being used as the root of the querySelectorAll, and for a modal that has not been rendered yet, the filter fields aren't found.  I notice that for searching for 'sortable' and 'grid-item', the root of the search is the parent of the element $element.parent().  When I change line 303 to

angular.forEach(angular.element(directiveElement[0].querySelectorAll('[filter-by]')), function (filter) {

similar to the registration of sortables, then filtering works in a modal.  I'm assuming there is a reason why the registration of filters starts from the document node (are there some filters that are very far from the data grid in the document node?).  Is the change I've made the right approach?  Or can you think of a better way to address it?  Thanks.

**Comment by AlexanderZhukCoherent** [comment]
Please provide working plunker or code sample of the issue in point. We've tried to reproduce it via Bootstrap modal - it works OK, even if modal is initially removed from DOM using ng-if. 
So we need to know what modal and how exactly you're using it; plunker / fiddle sample would be ideal.

**Comment by by12358** [comment]
Okay, I'll put something together.  Thanks for taking a look.
