### ISSUE TITLE
Pagination is not loading 

### ISSUE THREAD

**Issue by sevmardi** [angular-data-grid/angular-data-grid.github.io#19]
Hi!
Anyone else having trouble loading the pagination module into the app? 

As soon as I do so I get 

` Module 'pagination' is not available! You either misspelled the module name or forgot to load it`

```
angular.module('sxroApp', [
    'dataGrid',
    'pagination',

]);
```

If I check my gulp loaded file `vendor.js` I indeed can't find the module loaded. I can load the dataGrid though just fine.

**Comment by sskozzlovv** [comment]
You need to make sure that pagination.js(or pagination.min.js)  file is loaded in your html(<script src="../../dist/pagination.min.js"></script>) or included in your vendor.js file(if you are concatenating all js files in this one)

**Comment by david-hsn** [comment]
I'm getting the same error. 
:(
