### ISSUE TITLE
Working Server Side Pagination Example

### ISSUE THREAD

**Issue by markgerald** [angular-data-grid/angular-data-grid.github.io#20]
Is there any online example of server side paging? I could not work with the explanation in the manual, which is very bad.

**Comment by AlexanderZhukCoherent** [comment]
there is a server pagination example link on the main demo page: http://angular-data-grid.github.io/demo/bootstrap/server-pagination.html#/page=1&sort=orderNo-asc , please review and let us know if it work for you

**Comment by markgerald** [comment]
Codepen?

**Comment by AlexanderZhukCoherent** [comment]
will work on it soon; for now you can find it in sources: https://github.com/angular-data-grid/angular-data-grid.github.io/blob/master/demo/bootstrap/js/serverPaginationApp.js and
https://github.com/angular-data-grid/angular-data-grid.github.io/blob/master/demo/bootstrap/server-pagination.html

**Comment by markgerald** [comment]
this hi my load code in controller:

`$scope.gridOptions = {
                    data: [],
                    getData: getServerData,
                    sort: {
                        predicate: 'pagProId',
                        direction: 'asc'
                    }
                };

                function getServerData(callback) {
                    ProdutoService.query().$promise.then(function (data) {
                        callback(data.results, data.totalItems)
                    });
                  }
                };`

and this is html:

`<tr grid-item>
                        <td class="mdl-data-table__cell--non-numeric">
                            <span ng-bind="item.pagProId"></span>
                        </td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <img src="https://s3-us-west-2.amazonaws.com/pagpoucodev/{{item.pagProImagem}}" height="30" />
                        </td>
                        <td class="mdl-data-table__cell--non-numeric" ng-bind="item.pagProNome"></td>
                        <td class="mdl-data-table__cell--non-numeric" ng-bind="item.pagProCodigo"></td>
                        <td class="mdl-data-table__cell--non-numeric">
                            <a ui-sref="admin.editar-produto({id: item.pagProId})"><i
                                    class="mdi-editor-mode-edit text-md m-t-sm"></i></a>
                            <a ng-click="delete(item.pagProId, $event)"><i
                                    class="mdi-action-delete text-md m-t-sm"></i></a>
                        </td>
                    </tr>`

The grid returns blank, and there is no error message on the console.

**Comment by markgerald** [comment]
I tried to use your example in my code, and return an error; "callback is not a function"

**Comment by markgerald** [comment]
Thanks @AlexanderZhukCoherent ! is working!

Did you have an template example, using material for backend pagination?

**Comment by markgerald** [comment]
How can I redirect to route with params, like your example?? "page=1&sort=orderNo-asc" I use ui-router.

**Comment by markgerald** [comment]
Can you help me @AlexanderZhukCoherent ?

**Comment by markgerald** [comment]
???????

**Comment by AlexanderZhukCoherent** [comment]
@sskozzlovv Probably need to change '?' to '!' for the grid params to avoid conflict with standard params. 
ALSO, need to add CodePen for the server side sample.
