### ISSUE TITLE
Refresh grid on Client Side

### ISSUE THREAD

**Issue by Bilalriazwork** [angular-data-grid/angular-data-grid.github.io#23]
How can Refresh grid on client side. and database changing retrieve at client side.

**Comment by AlexanderZhukCoherent** [comment]
gridActions.refresh() or re-assigning of the data to gridOptions.data will do the trick.

**Comment by Bilalriazwork** [comment]
i have resolve this issue by using $scope.refresh() before assigning of the data to gridOptions.
thanks your response, i will also try with you method. Thanks
