### ISSUE TITLE
ngTransclude directive

### ISSUE THREAD

**Issue by rezanadimi72** [angular-data-grid/angular-data-grid.github.io#26]
hi
i see a problem in paging directive.
 the error is : `Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <ng-transclude>`

**Comment by sskozzlovv** [comment]
Fixed in e60daba. (Fixed problem when grid-item contains directive with ng-transclude in template)
