### ISSUE TITLE
Support fixed header columns?

### ISSUE THREAD

**Issue by KeyinLi** [angular-data-grid/angular-data-grid.github.io#29]
I was looking for material data table, and very pleasure to get nice one.
Is there a feature for fixed header columns or would be supported later?

**Comment by AlexanderZhukCoherent** [comment]
@KeyinLi Data Grid does not have any predefined template intentionally, to give users freedom to choose any layout they want. Fixed headers requires some predefined layout, hence it's not something we want to hardcode into grid as a permanent feature. However, we'll create some simple example how this can be done - planned as an enhancement for the next release.

**Comment by KeyinLi** [comment]
AlexZ,

Thank you very much, really appreciate your support.


On Apr 10, 2017, at 5:33 PM, AlexZ <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #29<https://github.com/angular-data-grid/angular-data-grid.github.io/issues/29> via 1842d57<https://github.com/angular-data-grid/angular-data-grid.github.io/commit/1842d577b3d94b888498a1e6fdd54a4a723bd962>.
