### ISSUE TITLE
Filtering not working after refresh with sorting enabled

### ISSUE THREAD

**Issue by AlexanderZhukCoherent** [angular-data-grid/angular-data-grid.github.io#31]
**Steps**
URL synchronization should be enabled for the grid. 
1. Apply some sorting 
2. Apply some filtering
3. Reload page (F5)
4. Change applied filtering

As a result, new filtering not working.

**Comment by AndreyChayko** [comment]
Issue closed, fixed in the scope of [#57](https://github.com/angular-data-grid/angular-data-grid.github.io/issues/57)
