### ISSUE TITLE
Ability to set a default search value when initializing the grid

### ISSUE THREAD

**Issue by ncahoon** [angular-data-grid/angular-data-grid.github.io#35]
I'd like to be able to load the grid with a pre-limited amount of data. For example, I'd like to be able to set the status filter drop down to the status "Valid" when the grid initializes. Is this possible?

**Comment by Cliff-Morrison** [comment]
Something I've been trying to get working as well.

**Comment by AndreyChayko** [comment]
Sure you can, just set the initial value for the associated filter ng-model:

```
        $scope.status = 'Valid';
```

**Comment by Cliff-Morrison** [comment]
When I set the initial value the filtering works properly.  However, when I clear the option form the drop down, the list is still filtered.  Refreshing the page, or clicking on a sortable header will reload the proper data.

**Comment by AndreyChayko** [comment]
@Cliff-Morrison Can you please provide more details about the issue you described above? We have checked the behavior on bootstrap and material sample on Chrome and IE browser
Our steps:
1) Set the init value to status filter
2) Open the page and see properly filtered data
3) Change the value to 'All Statuses'
4) Grid refreshes data and displays all records
