### ISSUE TITLE
Paging Remove issue

### ISSUE THREAD

**Issue by pankajsoftpowerbiz** [angular-data-grid/angular-data-grid.github.io#39]
Hi,

We are using angular data grid in a hybrid project (ionic, angular and cordova). Data is coming nicely in grid but we dont want to use paging and wanted to load all data in grid. but this is not working. We are using firebase to load data.

We are using below code to load all data .

 $scope.gridOptions = {
    data: UsersServ.index(),
    sort: {
      predicate: 'displayName',
      direction: 'asc'
    },
    showFilter: true,
    pagination: {
      itemsPerPage: -1
    }
  };

Please help us asap.
Best Regards,
P

**Comment by AndreyChayko** [comment]
The data grid updated, the default option of items per page has been removed, please take a look on the code pen sample [here](https://codepen.io/AngularDataGrid/pen/NvypOJ)
