### ISSUE TITLE
md-select doesn't display "paginationOptions.itemsPerPage"

### ISSUE THREAD

**Issue by NicolasMainardi** [angular-data-grid/angular-data-grid.github.io#42]
![image](https://cloud.githubusercontent.com/assets/29198773/26781579/8e63578a-49ef-11e7-95e9-7c6343bfb884.png)

Hi, I copied the Material Demo but md-select doesn't display "paginationOptions.itemsPerPage". Anyone had the same issue?

**Comment by ramboims** [comment]
I had the same issue, solved by setting 'value' property of md-option.

**Comment by AndreyChayko** [comment]
Material Design has been updated to the last version, MD samples updated appropriately, please take a look and give us feedback if issue is still reproducible
