### ISSUE TITLE
Don't see grid styles

### ISSUE THREAD

**Issue by srihari103** [angular-data-grid/angular-data-grid.github.io#44]
Any ideas why I don't see any styles for the grid?

![image](https://user-images.githubusercontent.com/7118615/26882608-785318f0-4b60-11e7-9381-194047a343e4.png)

**Comment by alexanderzhuk** [comment]
@srihari103 directive itself does not have any build-in styling, so you can use any. Bootstrap and Material Design samples use out-of-box versions of corresponding framework, like ```<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">``` so you can either use them or apply any other CSS you need.

**Comment by beardedlinuxgeek** [comment]
If you're already using AngularJS Material and don't want to load Material Design Lite, just compile this file:

https://github.com/google/material-design-lite/blob/mdl-1.x/src/data-table/_data-table.scss

and add it to your project
