### ISSUE TITLE
Sort icons do not show in IE in Material theme

### ISSUE THREAD

**Issue by fivage** [angular-data-grid/angular-data-grid.github.io#47]
In Chrome, it works fine.
In Bootstrap theme, it also works in IE, but not in Material theme.

see demo page: http://angular-data-grid.github.io/demo/material/

Rgds,
Filip

**Comment by AndreyChayko** [comment]
Samples were updated, the issue has been fixed, please take a look - [Material Design Theme](http://angular-data-grid.github.io/demo/material/)

**Comment by Thomasbehan** [comment]
How was this issue fixed? Experiencing the same issue
