### ISSUE TITLE
Filter won't work after sorting the data

### ISSUE THREAD

**Issue by pavanp73** [angular-data-grid/angular-data-grid.github.io#57]
For my data, I am doing following operations:
1. Filter
2. Sorted based on filter applied in step 1
3. I removed filter
Then, the model still holds the filter string which was applied in step 1. (Expected is: it should display all the data with sort applied in step 2)

**Comment by floraB90** [comment]
+1

**Comment by PabloMaly** [comment]
+1

**Comment by AndreyChayko** [comment]
Fixed, issue closed

**Comment by pavanp73** [comment]
Thank you.
