### ISSUE TITLE
Is it possible to extend the table row on click of the record?

### ISSUE THREAD

**Issue by KeyinLi** [angular-data-grid/angular-data-grid.github.io#66]
Hi Team,
Is it possible to extend the table row on click of the record.
For example, a table with more records exist and when the user clicked on particular row, the row should expand another table.

![28720787-328d9e50-737c-11e7-9ab7-f45f1de88583](https://user-images.githubusercontent.com/11389306/31212106-0ba22022-a964-11e7-93c6-c4030f97948c.png)

Thanks,
Keyin.

**Comment by AndreyChayko** [comment]
@KeyinLi 
At this time we are not planning to add such ability to the list of built in functionalities,
But you can use [this codepen](https://codepen.io/AngularDataGrid/pen/PEwNBv) like a pretty simple solution
