### ISSUE TITLE
Support for asp.net core MVC?

### ISSUE THREAD

**Issue by kprock** [angular-data-grid/angular-data-grid.github.io#69]
I apologize if this the wrong place to post this but I would love to implement this grid in an asp.net MVC project (.NET core 2.0). Is this possible given .NET Core's support for Angular SPAs?

Thanks in advance.

**Comment by peernova-azhuk** [comment]
This datagrid Angular directive is designed as data-source agnostic component. Data can come from any source / back-end system, no matter is it .NET. JAVA, PHP, NODE or something else. All you need is to give datagrid data as JS array. Not sure what you mean by '.NET Core's support for Angular SPAs', but this question is not related to this specific Angular DataGrid component per se.
